version: 2.1
jobs:
  maven-publish:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
            - maven-dependencies-
      - run:
          name: Import gpg key
          command: echo $GPG_KEY_BASE64 | base64 --decode | gpg --yes --batch --import
      - run:
          name: Set version
          command: |
            mvn versions:set -DnewVersion="$CIRCLE_SHA1"
            mvn versions:commit
      - run:
          name: Build artifact
          command: mvn clean package
      - save_cache:
          paths:
            - ~/.m2/repository
          key: maven-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Deploy to Maven Central
          command: mvn --settings .circleci/settings.xml deploy -Prelease -DskipTests

workflows:
  version: 2
  build_and_release:
    jobs:
      - maven-publish:
          context: Maven Central Release
          filters:
            branches:
              only: master
