name: Release (Github Package Registry)

on:
  push:
    branches:
    - 'master'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generer versjon og image navn
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=8 HEAD)
          VERSION=$TIME-$COMMIT
          echo "::set-env name=VERSION::"$VERSION""
      - run: mvn -B versions:set -DnewVersion="$VERSION"
      - run: mvn -B versions:commit
      - run: mvn -B --settings maven-settings.xml deploy -Dmaven.wagon.http.pool=false
      - uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
